### ISSUE TITLE
Remove unnecessary !! 

### ISSUE THREAD

**Issue by xanderblinov** [StephenVinouze/ShapeView#1]
Hi, why do you use "!!" everywhere ?

in case below you should better use local variable for path and finally setup property in your base class

`shapePath = Path()
        //top left corner
        shapePath!!.moveTo(width - innerRadius, innerMargin.toFloat())
        shapePath!!.lineTo(width - innerRadius, innerMargin.toFloat())`

in other cases you have to use ?.let{} expression

**Comment by StephenVinouze** [comment]
Hi,
Sorry for the late reply, didn't have time to look into it.
You're perfectly right, thanks for pointing me out. There are still many things that I ignore when it comes to Kotlin, but I'm getting there ;)
I'm releasing a patch right away!
Thanks again
